require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")
require("user.colorscheme")

require("user.cmp")
require("user.lsp")
require("user.coc")
require("user.dap")

require("user.telescope")
require("user.treesitter")
require("user.autopairs")

require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.spectre")
require("user.impatient")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.hop")
require("user.matchup")

require("user.closetag")
require("user.inlay-hints")
-- require("user.nerdcommenter")
require("user.move")
require("user.renamer")
require("user.rnvimr")
require("user.tabnine")
require("user.trouble")
require("user.sniprun")
-- require("user.ultisnips")

require("user.comment")
require("user.todo-comments")
require("user.surround")
require("user.notify")
require("user.ts-context")
require("user.illuminate")
