require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")
-- require("user.functions")
require("user.colorscheme")

require("user.cmp")
require("user.lsp")

require("user.yaml-companion")

require("user.dap")
require("user.dap-virtual-text")

require("user.telescope")
require("user.treesitter")
require("user.autopairs")

require("user.fidget")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.spectre")
require("user.impatient")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.hop")
require("user.matchup")

require("user.closetag")
require("user.inlay-hints")
require("user.move")
require("user.renamer")
require("user.lf")

require("user.chatgpt")
require("user.tabnine")

require("user.jaq")
require("user.sniprun")

require("user.orgmode")
require("user.go")
require("user.bullets")
require("user.comment")
require("user.todo-comments")
require("user.surround")
require("user.notify")
require("user.ts-context")
require("user.illuminate")
require("user.toggler")
